spring.application.name=Ticket-Booking

# Connection with PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketbooking_db
spring.datasource.username=lang123
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#PORT SERVER
server.port=9181

# JWT for Generate Token
jwt.secret=7d05519c9d30332993b8103637c6d0450473103d90b859c8dae78bdfdc767e04017f52da3611da807e14bf866e3d26bd653bbddcdac5f0a375d405a3bce8fba7
jwt.expiration=86400000